Issue 8 2 공통 exception추가
f-lab-edu/logout pull request #17
Opened 2023-08-29 16:40 UTC by kimunche

생성일 수정일 엔터티를 공통으로 뺴고 공통 exception 추가함

2023-09-02 15:27 UTC, f-lab-moony requested changes
고생 많으셨어요 ~
코멘트를 좀 남겨 뒀는데, 확인 후 리뷰 재요청 부탁드립니다 ~

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/controller/OwnerController.java
> +    public void deleteOwner(@PathVariable("ownerId") String id) {
이거 위에 path랑 매핑 되나요 ?

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/controller/ReservationController.java
> +    @GetMapping()
`()` 없어도 될거같아요 ~

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/controller/request/owner/OwnerCreateRequest.java
> +package com.example.hotelproject.controller.request.owner;
패키지 구조도 다시 한번 생각해보는게 좋을 것 같아요~
만약 모듈을 분리 할 일이 생겼을 때, controller / request / response 처럼 분리 할 것인지 owner / hotel / payment 처럼 분리 할 것인지, 둘 중에 어떤 게 나을까요 ?

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/controller/request/payment/PayCreateRequest.java
> +    @NonNull
요거 여기에만 붙인 이유가 있을까요 ~?
+ 이 어노테이션이 적용되려면 어떻게 해야 할까요 ?

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/controller/request/payment/PayCreateRequest.java
> +    public PayCreateRequest(@NonNull PayType payType, @NonNull Long amount, @NonNull String orderName, String yourSuccessUrl, String yourFailUrl) {
필드와 이 파라미터에 같이 적용한 이유가 있을까요 ?
실제 요청이 들어올 때, 둘 중 어떤 어노테이션이 적용될까요 ?

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/controller/request/payment/PayCreateRequest.java
> +            .paySuccessYN(false)
요거는 차라리 디폴트 값을 지정하는게 낫지 않을까요 ?

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/controller/request/payment/PayCreateRequest.java
> +            .orderId(UUID.randomUUID().toString())
호텔을 예약할 수 있는 서비스 입장에서 예약은 주문과 동일한 것 같은데, 예약 id를 넣어도 되지 않을까요 ?

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/controller/response/payment/PaymentResponse.java
> +@AllArgsConstructor
`@AllArgsConstructor` 쓰기를 지양해야 하는 이유가 뭘까요 ~?

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/controller/response/payment/PaymentResponse.java
> +@Builder
`@Builder` 를 클래스에 선언하면 안좋은 이유가 뭘까요 ~?

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/domain/Reservation.java
> +    @Column(name = "reservation_id")
컬럼 이름을 reservation_id로 바꾼 이유가 있을까요 ?

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/domain/Reservation.java
> +//    @CreatedDate
안쓰는 주석은 지워주는 습관을 들이는게 좋을 것 같아요 ~

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/service/ReservationService.java
> +        return reservationRepository.findAllByUser_UserNoAndCancelDateIsNull(userNo).stream()
cancelDate의 유무로 판단하기보단 canceled 필드를 선언해서 사용하는게 어떨까요 ~?

2023-09-02 15:27 UTC, f-lab-moony commented on src/main/java/com/example/hotelproject/service/ReservationService.java
> +        return reservationRepository.findAllByUser_UserNoAndCancelDateIsNull(userNo).stream()
추가로, canceled 필드를 따로 만들면, Entity 클래스에 `@Where` 어노테이션으로 미리 거를수도 있을 것 같아요 ~

2023-09-03 14:18 UTC, kimunche commented on src/main/java/com/example/hotelproject/controller/OwnerController.java
> +    public void deleteOwner(@PathVariable("ownerId") String id) {
수정완료!

2023-09-03 14:18 UTC, kimunche commented on src/main/java/com/example/hotelproject/controller/ReservationController.java
> +    @GetMapping()
수정완료

2023-09-03 14:20 UTC, kimunche commented on src/main/java/com/example/hotelproject/controller/request/owner/OwnerCreateRequest.java
> +package com.example.hotelproject.controller.request.owner;
도메인별>controller/ request / response /  entity 로 나누는게 좋을것같아용..! 
다음과 같이 나눌까 합니다
ex) hotel > controller/ request / response /  entity
owner> controller/ request / response /  entity

2023-09-03 14:31 UTC, kimunche commented on src/main/java/com/example/hotelproject/controller/request/payment/PayCreateRequest.java
> +    @NonNull
앗 아마 @AllArgsConstructor 적용했을때 붙였던걸 안뗀거같습니다,,
@NonNull 을 필드에 사용했을때는 롬복이 자동생성한 메서드나 생성자에만 적용이 되고 제가 작성한 메서드에는 적용되지 않습니다

2023-09-03 14:33 UTC, kimunche commented on src/main/java/com/example/hotelproject/controller/request/payment/PayCreateRequest.java
> +    public PayCreateRequest(@NonNull PayType payType, @NonNull Long amount, @NonNull String orderName, String yourSuccessUrl, String yourFailUrl) {
필드랑 파라미터에 둘다 @NonNull을 붙이게 되면 여기 어노테이션이 적용이되지 않을까..요..?????

2023-09-03 14:36 UTC, kimunche commented on src/main/java/com/example/hotelproject/controller/response/payment/PaymentResponse.java
> +@AllArgsConstructor
모든 필드의 생성자를 자동생성해주기 때문에, 접근할 필요가 없는 필드값에 대해서 접근할 수 있을 수 있는 문제(접근성 최대화)

2023-09-03 14:45 UTC, kimunche commented on src/main/java/com/example/hotelproject/controller/response/payment/PaymentResponse.java
> +@Builder
@AllArgsConstructor 와 동일한 효과를 낼수있기 때,,문에?.??

2023-09-03 14:45 UTC, kimunche commented on src/main/java/com/example/hotelproject/domain/Reservation.java
> +    @Column(name = "reservation_id")
테이블마다 id 라고 하니 좀 헷갈려서 table name+ id 로 수정했습니당

2023-09-03 14:46 UTC, kimunche commented on src/main/java/com/example/hotelproject/domain/Reservation.java
> +//    @CreatedDate
수정완료

2023-09-03 14:54 UTC, kimunche commented on src/main/java/com/example/hotelproject/service/ReservationService.java
> +        return reservationRepository.findAllByUser_UserNoAndCancelDateIsNull(userNo).stream()
수정완료

2023-09-08 17:39 UTC, merged